version: '2'
services:
    scalemanager-api:
        build:
            - context: tests/fixtures/Dockerfile-nginx
        ports:
            - "82:80"
        links:
            - scalemanager-php
    scalemanager-php:
        image: php:7.1-fpm
        ports:
            - "9002:9000"
        volumes:
            - "src/public:/var/www/html"
    scalemanager-eventlog-db:
        image: mysql/mysql-server
        ports:
            - "3308:3306"
        environment:
            - MYSQL_USER=scalemanager-eventlog
            - MYSQL_PASSWORD=scalemanager-eventlog
            - MYSQL_DATABASE=scalemanager-eventlog
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
    scalemanager-actionlog-db:
        image: mysql/mysql-server
        ports:
            - "3310:3306"
        environment:
            - MYSQL_USER=scalemanager-actionlog
            - MYSQL_PASSWORD=scalemanager-actionlog
            - MYSQL_DATABASE=scalemenager-actionlog
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=true